### PR TITLE
Update for GeometricIntegrators v0.6 and add new integrators.

### PR DESCRIPTION
**Pull request by michakraus**

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Thanks. Did https://github.com/SciML/DiffEqDocs.jl/commit/578cbd9e278d147a46d1ee2e122e151b7bdfe217 concurrently, and the last details in the docs of it can get filled in soon. Really nice to see the Labatto methods: since we've focused mostly on adaptive methods, the symplectic methods haven't been the biggest focus and knowing you've done it means it's probably fairly optimal.

It would be nice to get the SDE tools connected as well.

**Comment by michakraus** [comment]
Thanks for taking care of the docs. Good point with the SDE integrators. I think also more of the partitioned methods should be connected, especially in sight of the Lobatto methods. But I think there is a little work needed on our side as well, as the respective constructors have not been updated, yet (I think).

Since some time we also have a slick mid-level interface for calling the integrators, exchanging only a small data structure in each integration step. It might make sense to interface at this level instead of performing a full run with GeometricIntegrators and converting the solution.

**Comment by ChrisRackauckas** [comment]
That is definitely a good idea.

**Comment by michakraus** [comment]
I will add more of the partitioned methods in the next round of upgrading GeometricIntegratorsDiffEq.jl to GeometricIntegrators v0.7.
We also have a lot of variational integrators, which require an implicit equation. That seems something worth adding as well. Here and for the stochastic methods, I'll probably need a little help with converting the equations.

For the migration to the mid-level interface, I will document the API when I have a little time. Then we can discuss how to proceed.

**Comment by ChrisRackauckas** [comment]
That sounds great. I'll wait on the documentation of that API. I have a few proposals to write in the meantime anyways. Figuring out an interface on the variational integrators would be great too: it's something we've previously ignored since there weren't any solvers. But we should do this now. I assume it will need more than just the implicit DAE interface as it will need some way of specifying partitions to the equation?

**Comment by michakraus** [comment]
For "standard" Lagrangians (i.e. non-degenerate) one only needs the two derivatives of the Lagrangian ∂L/∂x and ∂L/∂v if L=L(x,v). In terms of a general implicit equation dp/dt = f(x,v), p=g(x,v), this amounts to specifying f and g. For degenerate Lagrangians, one needs to specify the projection ∇g⋅v in addition.

**Comment by michakraus** [comment]
PS: I am working on a package for Euler-Lagrange equations (based on MTK), that can generate all the code necessary automatically, including all the pieces required for degenerate Lagrangians and more complicated systems, e.g., with  constraints. It might make sense to also have a DifferentialEquations.jl bridge for that...

**Pull request merged**
